version: '3.8'
services:
  app:
    volumes:
      - setup-python-project-cache-pre-commit:/home/python/.cache/pre-commit
      - setup-python-project-vscode-extensions:/home/python/.vscode-server/extensions

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

volumes:
  setup-python-project-cache-pre-commit:
  setup-python-project-vscode-extensions:
